### ISSUE TITLE
Sequential Playback not working

### ISSUE THREAD

**Issue by Superchimp** [temportalflux/MusicAssist#15]
First of all thank you for this fantastic Module! It's brilliant for people like me with limited upload speeds and really appreciate it. I have come to notice an issue though, sequential playback with FVTT (v0.6.4) works fine with local hosted files, but does not work using playlists with streamed files using your Module. When pressing play for the playlist while in sequential mode it only plays the first song and does not move onto the next.

I've run a series of tests, here are the results:

Sequential play from Locale file to Local file  = Pass
Sequential play from Streamed file to Streamed file = Fail
Sequential play from Streamed file to Local file = Fail
Sequential play from Local file to Streamed file = Fail

It's as if FVTT doesn't realise the track has ended. Hope it is possible to fix and thanks again for adding some audio to my sessions.

**Comment by Superchimp** [comment]
Side note, sequential play doesn't work within a playlist either. Seems that the module and Youtube are not communicating correctly to play the next song in either an FVTT playlist or a Youtube playlist.

**Comment by scarymike23** [comment]
Seeing the same. Playlists will only play one track and then stop.

**Comment by LeifKlover** [comment]
Can confirm that this is still indeed the case.

**Comment by casualchameleon** [comment]
This has been fixed in my fork. Sequential and shuffle both work.

**Comment by temportalflux** [comment]
MusicAssist has been deprecated, and forked/continued by its successor, Bellows https://github.com/casualchameleon/Bellows
