### ISSUE TITLE
After leaving a session and later returning, music does not play

### ISSUE THREAD

**Issue by bryancasler** [temportalflux/MusicAssist#20]
I've noticed this running 0.6.6 with both D&D and Pathfinder game systems that after leaving the world and returning at a later time the audio does not play. However if you go to the Audio Playlist tab, it visually indicates that it should be playing. You can simply stop/start it to get it going again. But it would be nice if it auto-played as expected.

**Comment by casualchameleon** [comment]
This has been fixed in my fork

**Comment by bryancasler** [comment]
@casualchameleon Thanks so much for the heads up. Will be switching over to your fork and giving it a try.
