### ISSUE TITLE
Problem with multiple Ambient sounds with youtube streamed audio

### ISSUE THREAD

**Issue by markhop1** [temportalflux/MusicAssist#25]
Hello everyone!

I was trying to set up an adventure when I found this rare issue. Apparently, the first ambient sound I place with Streamed audio Url (youtube) works properly, but since that the following Ambient Sounds with Streamed audio URL **play the same sound from the first one** instead of the one I set. 

This issue doesn't reproduce with local based files.

**Comment by casualchameleon** [comment]
This is fixed in my fork

**Comment by temportalflux** [comment]
Depreciation announcement added to Readme!
