### ISSUE TITLE
Tons of youtube resource requests when initially loading/refreshing foundry

### ISSUE THREAD

**Issue by ellroch** [temportalflux/MusicAssist#28]
I've got a half dozen playlists ~5-10 songs each linked to youtube. this doesnt cause any issues during play, but it seriously slows down load time... 

![image](https://user-images.githubusercontent.com/16342145/103084573-f0b0be00-45a4-11eb-80c4-8de7bddd27f5.png)

pretty much every one of the 6900 errors (barring 5-6 from other modules before I started building out my playlists)  is from a denied resource request on load to youtube.

I'm not sure how necessary it is to make these requests, but they don't seem to be getting fulfilled, and they are noticably slowing the system down... is it possible to trim them?

**Comment by ellroch** [comment]
by trim them, I mean wait until the track is played to make the resource request.

**Comment by temportalflux** [comment]
MusicAssist has been deprecated, and forked/continued by its successor, Bellows https://github.com/casualchameleon/Bellows
