### ISSUE TITLE
Youtube track loading multiple requests for each item during loading

### ISSUE THREAD

**Issue by Alarich** [temportalflux/MusicAssist#7]
Greetings, thanks for the module, it's quite promising. 

I've run into a slight issue when using youtube videos as streamable playlist entries. Namely, there are multiple requests made per playlist entry (seems like 7-8), where it's probably creating either an iframe or adding a script tag somewhere that causes youtube to start ramping up its' css/js requests and events.

This is part of the log when there were 44 tracks in the playlist (all youtube links):
![image](https://user-images.githubusercontent.com/5496089/82769018-2a68ed00-9e3b-11ea-8a72-815c251d24e7.png)

As you can probably see, that's quite excessive. 
What's more, this was being done even when it was the player that had logged in, without having access to the playlist.

Unless there's some technical limitation, I would suggest that the videos should not be all loaded during bootup, but only when actually played. Even if that takes longer for the track to start.

**Comment by casualchameleon** [comment]
Fixed in my fork.

**Comment by Alarich** [comment]
I see there are PRs that were merged quite recently. @temportalflux is MusicAssist going to be abandoned in favor of the newly rebranded Bellows? 

I've suggested MusicAssist to people who ask about youtube audio sources on The Forge, but it seems Bellows is maintained slightly more.

I don't mean to cause a fight about who done it better :D

**Comment by temportalflux** [comment]
Haha you're all good! I haven't had a chance to change the Readme yet, but casualchameleon and I have been chatting (and they've been helping me bring in their changes as needed). MusicAssist is indeed going to be deprecated, it was only ever just a small adventure/curiosity (which is why I never added it to the public modules page for FoundryVTT).
