### ISSUE TITLE
Sound Stream Does not stop playing when moving on to a uploaded asset in foundry.

### ISSUE THREAD

**Issue by Sunamon** [temportalflux/MusicAssist#9]
So if have a play list in foundry with a mix of youtube streams and local assets when switching from a youtube stream to a local asset it doesn't stop playing the youtube stream.

**Comment by casualchameleon** [comment]
This is fixed in my fork

**Comment by temportalflux** [comment]
MusicAssist has been deprecated, and forked/continued by its successor, Bellows https://github.com/casualchameleon/Bellows
